### ISSUE TITLE
Unexpected identifier on nextjs

### ISSUE THREAD

**Issue by georgjaehnig** [volkov97/react-compound-timer#12] opened 2019-06-26 14:06 UTC
Hi,

I'm having a working [nextjs](https://nextjs.org/) project and just tried to import `react-compound-timer` via:

    import React, {Component} from "react";
    import Timer from "react-compound-timer";

Only adding the `import Timer` line gives me:

    SyntaxError: Unexpected identifier
    (anonymous function)
    <my project path>/node_modules/react-compound-timer/build/index.js:1
    new Script
    vm.js:84:7
    createScript
    vm.js:264:10
    runInThisContext
    vm.js:312:10
    Module._compile
    internal/modules/cjs/loader.js:694:28
    Module._extensions..js
    internal/modules/cjs/loader.js:745:10
    Module.load
    internal/modules/cjs/loader.js:626:32
    tryModuleLoad
    internal/modules/cjs/loader.js:566:12
    Function.Module._load
    internal/modules/cjs/loader.js:558:3
    Module.require
    internal/modules/cjs/loader.js:663:17
    require
    internal/modules/cjs/helpers.js:20:18
    react-compound-timer
    webpack:/external "react-compound-timer":1
    > 1 | module.exports = require("react-compound-timer");
    View compiled
  
    __webpack_require__
    ./webpack/bootstrap:21
      18 | // Execute the module function
      19 | var threw = true;
      20 | try {
    > 21 | 	modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
         | ^  22 | 	threw = false;
      23 | } finally {
      24 | 	if(threw) delete installedModules[moduleId];
    View compiled
  
    Module../pages/index.js
    /_next/development/server/static/development/pages/index.js:685:78
    __webpack_require__
    ./webpack/bootstrap:21
      18 | // Execute the module function
      19 | var threw = true;
      20 | try {
    > 21 | 	modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
         | ^  22 | 	threw = false;
      23 | } finally {
      24 | 	if(threw) delete installedModules[moduleId];
    View compiled
  
    3
    /_next/development/server/static/development/pages/index.js:3419:18
    __webpack_require__
    ./webpack/bootstrap:21
      18 | // Execute the module function
      19 | var threw = true;
      20 | try {
    > 21 | 	modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
         | ^  22 | 	threw = false;
      23 | } finally {
      24 | 	if(threw) delete installedModules[moduleId];
    View compiled

I wonder – since you are using Typescript – maybe do I need to somehow reference that? (I'm very new to React.)

**Comment by kousu** [comment] 2019-07-29 06:02
I don't think this is your mistake. This is probably a duplicate of #11. Can you try installing #14 -- or wait for @volkov97 to merge that and republish to npm -- and see if the problem goes away?

**Comment by volkov97** [comment] 2020-03-19 14:26
Should be working in 1.2.0, if not - please, reopen this issue. Thanks!

**Closed as completed by volkov97** 2020-03-19 14:26 UTC
